#!/usr/bin/env python3
"""Interactive udev-naming wizard for the YAM station's CAN adapters.

Fresh machines enumerate the four CAN-USB adapters as ``can0..can3`` in plug order, but
the station expects stable role names (``can_left``, ``can_right``, ``can_lead_l``,
``can_lead_r``). Rather than unplugging cables one at a time and taking notes:

    python scripts/setup_can_udev.py            # 4-role bimanual station
    python scripts/setup_can_udev.py --roles can_right,can_lead_r   # single arm
    python scripts/setup_can_udev.py --print-only                   # no write

Per role: unplug that device, watch ``/sys/class/net`` for the interface that disappears,
record its fixed USB-Hub downstream port, plug back in — the last role is inferred from
what remains. Then it generates ``/etc/udev/rules.d/70-yam-can.rules``, shows it for
approval, writes it via sudo (the only step needing root), reloads udev, and tells you
to replug. The rule binds the role to the USB port, not to a robot body serial number
or to the adapter serial number.

Read-only until that confirmed write, and it never sends a CAN frame, so arm/leader power
state does not matter — only USB presence does.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import time
from pathlib import Path

DEFAULT_ROLES = [
    # (interface name to assign, human prompt)
    ("can_left", "LEFT follower arm"),
    ("can_right", "RIGHT follower arm"),
    ("can_lead_l", "LEFT leader"),
    ("can_lead_r", "RIGHT leader"),
]
RULES_PATH = "/etc/udev/rules.d/70-yam-can.rules"


def can_interfaces() -> set[str]:
    root = Path("/sys/class/net")
    if not root.is_dir():
        return set()
    return {p.name for p in root.iterdir() if p.name.startswith("can")}


def usb_port_of(iface: str) -> str | None:
    """The USB-Hub downstream port for a CAN interface (for example ``5-2.1``)."""
    proc = subprocess.run(
        ["udevadm", "info", "--query=path", "--path", f"/sys/class/net/{iface}"],
        capture_output=True, text=True, check=False,
    )
    m = re.search(r"/((?:\d+-\d+)(?:\.\d+)*):[^/]+/net/", proc.stdout)
    return m.group(1) if m else None


def generate_rules(mapping: dict[str, str]) -> str:
    """udev rules text for a {role_name: USB-Hub downstream port} mapping."""
    lines = [
        "# YAM station CAN adapter names — generated by scripts/setup_can_udev.py",
        "# One line per fixed USB-Hub downstream port; names must start with 'can' (max 13 chars).",
    ]
    for name, port in mapping.items():
        lines.append(
            f'SUBSYSTEM=="net", ACTION=="add", KERNELS=="{port}", NAME:="{name}"'
        )
    return "\n".join(lines) + "\n"


def wait_for_change(before: set[str], want_removed: bool, timeout: float = 120.0) -> str | None:
    """Block until an interface disappears from (or reappears in) ``before``."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        now = can_interfaces()
        diff = (before - now) if want_removed else (now - before)
        if len(diff) == 1:
            return diff.pop()
        if len(diff) > 1:
            print(f"  ! more than one interface changed at once ({sorted(diff)}); "
                  "replug and try again")
            return None
        time.sleep(0.3)
    return None


def identify(roles: list[tuple[str, str]]) -> dict[str, str] | None:
    """Walk the unplug/replug dance; returns {role_name: USB-Hub port}."""
    start = can_interfaces()
    print(f"detected CAN interfaces: {sorted(start) or 'none'}")
    if len(start) != len(roles):
        print(f"error: expected {len(roles)} adapters for roles "
              f"{[r for r, _ in roles]}, found {len(start)}. "
              "Plug in all adapters (arm power not required) or pass --roles.")
        return None

    ports: dict[str, str] = {}
    remaining = set(start)
    for i, (name, label) in enumerate(roles):
        if i == len(roles) - 1:  # last one is whatever is left
            iface = remaining.pop()
            port = usb_port_of(iface)
            print(f"[{name}] inferred from the remaining adapter ({iface}, USB port {port})")
            if port is None:
                return None
            ports[name] = port
            break
        input(f"\n[{name}] UNPLUG the USB cable of the {label}, then press Enter... ")
        gone = wait_for_change(can_interfaces() | remaining, want_removed=True, timeout=60)
        if gone is None or gone not in remaining:
            print("  ! could not identify a single removed interface; aborting")
            return None
        port = port_of_cache.get(gone)
        print(f"  -> {label} = {gone} (USB port {port})")
        if port is None:
            print("  ! no USB port recorded for that interface; aborting")
            return None
        ports[name] = port
        remaining.discard(gone)
        input(f"  plug the {label} back in, then press Enter... ")
        wait_for_change(can_interfaces(), want_removed=False, timeout=60)
    return ports


port_of_cache: dict[str, str | None] = {}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--roles", default=",".join(r for r, _ in DEFAULT_ROLES),
                    help="comma-separated interface names to assign, in prompt order")
    ap.add_argument("--print-only", action="store_true",
                    help="identify and print the rules, but do not write or reload")
    ap.add_argument("--selftest", action="store_true", help=argparse.SUPPRESS)
    args = ap.parse_args()

    if args.selftest:  # exercises the pure rule generator (no hardware needed)
        out = generate_rules({"can_left": "5-2.3", "can_lead_l": "5-2.1"})
        assert 'KERNELS=="5-2.3", NAME:="can_left"' in out
        assert 'KERNELS=="5-2.1", NAME:="can_lead_l"' in out
        assert all(len(n) <= 13 for n in ("can_left", "can_lead_l"))
        print("selftest OK")
        return 0

    labels = {name: label for name, label in DEFAULT_ROLES}
    roles = [(r.strip(), labels.get(r.strip(), r.strip())) for r in args.roles.split(",") if r.strip()]
    for name, _ in roles:
        if not name.startswith("can") or len(name) > 13:
            print(f"error: '{name}' must start with 'can' and be <=13 chars")
            return 1

    # Pre-cache USB ports so we can resolve an interface after it disappears.
    for iface in can_interfaces():
        port_of_cache[iface] = usb_port_of(iface)

    mapping = identify(roles)
    if not mapping:
        return 1

    rules = generate_rules(mapping)
    print("\n--- generated rules ---------------------------------------")
    print(rules, end="")
    print("------------------------------------------------------------")
    if args.print_only:
        print(f"(--print-only: not writing {RULES_PATH})")
        return 0

    if input(f"write to {RULES_PATH} and reload udev? [y/N] ").strip().lower() != "y":
        print("aborted; nothing written")
        return 1
    proc = subprocess.run(["sudo", "tee", RULES_PATH], input=rules,
                          capture_output=True, text=True)
    if proc.returncode:
        print(f"write failed: {proc.stderr.strip()}")
        return 1
    subprocess.run(["sudo", "udevadm", "control", "--reload-rules"], check=False)
    subprocess.run(["sudo", "udevadm", "trigger"], check=False)
    print("\ndone. Now UNPLUG and REPLUG all adapters once — the interfaces will "
          "come back with their new names. Verify with:  ip link show | grep can")
    return 0


if __name__ == "__main__":
    sys.exit(main())
